import { StyleSheet } from "react-native";

import type { ColorSet, Spacing, Typography } from "@/theme/types";

export const makeStyles = (
  theme: ColorSet,
  spacing: Spacing,
  typography: Typography
) =>
  StyleSheet.create({
    container: {
      marginTop: spacing.lg,
      marginBottom: spacing.md,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: spacing.md,
      paddingHorizontal: 4,
    },
    sectionTitle: {
      ...typography.smallCaption,
      color: theme.textSecondary,
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 1.8,
      opacity: 0.9,
    },
    topGrid: {
      flexDirection: "row",
      gap: spacing.md,
    },
    fullWidthStack: {
      marginTop: spacing.md,
    },
    compactCard: {
      flex: 1,
      minHeight: 168,
      borderRadius: 24,
      overflow: "hidden",
      backgroundColor: theme.cardRaised ?? theme.surface ?? "#262A22",
      borderWidth: 1,
      borderColor: theme.borderMuted ?? "rgba(255,255,255,0.06)",
      padding: spacing.md,
      shadowColor: theme.shadow ?? "#000",
      shadowOpacity: 0.22,
      shadowOffset: { width: 0, height: 10 },
      shadowRadius: 18,
      elevation: 6,
    },
    wideCard: {
      minHeight: 94,
      borderRadius: 24,
      overflow: "hidden",
      backgroundColor: theme.cardRaised ?? theme.surface ?? "#262A22",
      borderWidth: 1,
      borderColor: theme.borderMuted ?? "rgba(255,255,255,0.06)",
      paddingHorizontal: spacing.md,
      paddingTop: spacing.md,
      paddingBottom: spacing.sm,
      shadowColor: theme.shadow ?? "#000",
      shadowOpacity: 0.22,
      shadowOffset: { width: 0, height: 10 },
      shadowRadius: 18,
      elevation: 6,
    },
    cardPressed: {
      opacity: 0.94,
      transform: [{ scale: 0.992 }],
    },
    cardDisabled: {
      opacity: 0.72,
    },
    compactInner: {
      flex: 1,
      justifyContent: "space-between",
    },
    compactTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
    },
    hydrationIconWrap: {
      width: 42,
      height: 42,
      borderRadius: 21,
      borderColor: theme.accent ?? "rgba(255,255,255,0.14)",
      shadowColor: theme.shadow ?? "#000",
      shadowOpacity: 0.2,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 10,
      elevation: 3,
    },
    iconWrap: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
    },
    compactMetricGroup: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    compactMetric: {
      fontSize: 11,
      lineHeight: 14,
      fontWeight: "700",
      color: theme.textSecondary,
      opacity: 0.92,
      letterSpacing: 0.2,
    },
    compactChevron: {
      marginTop: 1,
      opacity: 0.92,
    },
    compactBody: {
      flex: 1,
      justifyContent: "center",
      paddingTop: spacing.lg,
      paddingBottom: spacing.sm,
    },
    kicker: {
      fontSize: 10,
      lineHeight: 13,
      fontWeight: "700",
      letterSpacing: 1.7,
      color: theme.textSecondary,
      opacity: 0.6,
      marginBottom: 4,
    },
    compactTitle: {
      ...typography.h3,
      fontSize: 19,
      lineHeight: 22,
      color: theme.textPrimary,
      fontWeight: "700",
      letterSpacing: -0.2,
    },
    wideInner: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.md,
    },
    wideIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
    },
    wideTextBlock: {
      flex: 1,
      justifyContent: "center",
    },
    wideTitle: {
      ...typography.h3,
      color: theme.textPrimary,
      fontSize: 19,
      lineHeight: 22,
      fontWeight: "700",
      letterSpacing: -0.2,
    },
    wideMetric: {
      fontSize: 20,
      lineHeight: 24,
      fontWeight: "700",
      color: theme.accent,
      fontStyle: "italic",
      letterSpacing: 0.1,
      textAlign: "right",
    },
    wideMetricGroup: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    wideChevron: {
      marginTop: 1,
      opacity: 0.92,
    },
    wideProgressWrap: {
      marginTop: spacing.sm,
    },
    progressTrack: {
      height: 4,
      borderRadius: 999,
      backgroundColor: theme.divider ?? "rgba(255,255,255,0.08)",
      overflow: "hidden",
    },
    progressFill: {
      height: "100%",
      borderRadius: 999,
    },
    skeletonCard: {
      flex: 1,
      minHeight: 168,
      borderRadius: 24,
      backgroundColor: theme.cardRaised ?? theme.surface ?? "#262A22",
      borderWidth: 1,
      borderColor: theme.borderMuted ?? "rgba(255,255,255,0.06)",
      padding: spacing.md,
    },
    skeletonWide: {
      minHeight: 94,
      borderRadius: 24,
      backgroundColor: theme.cardRaised ?? theme.surface ?? "#262A22",
      borderWidth: 1,
      borderColor: theme.borderMuted ?? "rgba(255,255,255,0.06)",
      paddingHorizontal: spacing.md,
      paddingTop: spacing.md,
      paddingBottom: spacing.sm,
    },
    skeletonTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
    },
    skeletonIcon: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.surfaceMuted ?? "rgba(255,255,255,0.05)",
    },
    skeletonMetric: {
      width: 34,
      height: 12,
      borderRadius: 999,
      backgroundColor: theme.surfaceMuted ?? "rgba(255,255,255,0.05)",
    },
    skeletonBody: {
      flex: 1,
      justifyContent: "center",
      paddingTop: spacing.lg,
      paddingBottom: spacing.sm,
    },
    skeletonKicker: {
      width: 44,
      height: 8,
      borderRadius: 999,
      backgroundColor: theme.surfaceMuted ?? "rgba(255,255,255,0.05)",
      marginBottom: 10,
    },
    skeletonTitle: {
      width: "72%",
      height: 14,
      borderRadius: 999,
      backgroundColor: theme.surfaceMuted ?? "rgba(255,255,255,0.05)",
    },
    skeletonProgress: {
      height: 4,
      borderRadius: 999,
      backgroundColor: theme.surfaceMuted ?? "rgba(255,255,255,0.05)",
    },
    skeletonWideRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.md,
      marginBottom: spacing.sm,
    },
    skeletonWideIcon: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.surfaceMuted ?? "rgba(255,255,255,0.05)",
    },
    skeletonWideText: {
      flex: 1,
      height: 12,
      borderRadius: 999,
      backgroundColor: theme.surfaceMuted ?? "rgba(255,255,255,0.05)",
    },
    skeletonWideMetric: {
      width: 52,
      height: 14,
      borderRadius: 999,
      backgroundColor: theme.surfaceMuted ?? "rgba(255,255,255,0.05)",
    },
    errorCard: {
      borderRadius: 24,
      minHeight: 96,
      backgroundColor: theme.cardRaised ?? theme.surface ?? "#262A22",
      borderWidth: 1,
      borderColor: theme.borderMuted ?? "rgba(255,255,255,0.06)",
      padding: spacing.md,
      justifyContent: "center",
      alignItems: "center",
    },
    errorTitle: {
      color: theme.textPrimary,
      fontSize: 14,
      fontWeight: "700",
      textAlign: "center",
    },
    errorSubtitle: {
      color: theme.textSecondary,
      fontSize: 12,
      marginTop: 4,
      textAlign: "center",
    },
  });

export type BiometricBlueprintStyles = ReturnType<typeof makeStyles>;
